[package]
name = "Portal_StillAlive_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.29.0"
ctrlc = "3.4.7"
ratatui = "0.29.0"
rodio = "0.20.1"
