[package]
name = "Portal_StillAlive_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.1"
rodio = "0.20.1"
once_cell = "1.20.2"
chrono = "0.4.38"
