
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: portal-still-alive-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: portal-still-alive-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: portal-still-alive-macos

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev pkg-config
        
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install pkg-config
        
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Build
      run: cargo build --release --verbose
      
    - name: Prepare binary
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/release/*.exe ${{ matrix.asset_name }}
        else
          cp target/release/Portal_StillAlive_Rust ${{ matrix.asset_name }}
        fi
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
